version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: grid-game-postgres
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass123
      POSTGRES_DB: gridgame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser -d gridgame"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: grid-game-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: